### ISSUE TITLE
TypeError: Cannot read property 'callback' of undefined

### ISSUE THREAD

**Issue by orangebook** [Automattic/kue#1002]
There has same error : https://github.com/NodeRedis/node_redis/issues/1037
But I don't know how to solve it.
@alexkwolfe @folletto @frosty @markryall 
I have a clean code by this error
before code ,there has 
```json
 "redis": "^2.6.3",
 "kue": "^0.11.5"
```

follow code in **TaskHandler.js**

```
const redis = require('redis')
    , kue = require('kue')
    , jobs = kue.createQueue()
    , SyncData = require('./SyncDataByGet.js')
    , debug = require('debug')('TaskExecutor.js');

exports = module.exports = function () {
    jobs.process("sysTask", 3, function (job, done) {
        try {
            let sysTask = job.data;
            debug(sysTask);
            SyncData.task(sysTask["device_ip"], sysTask['start_time'], sysTask['end_time']).then(function (result) {
                job.progress(100, 100, "OK");
                done();
            }).catch(function (err) {
                debug(err);
            });
        } catch (error) {

        }
    });
};
```
then ,I use it by this code
```
require('TaskHandler')();
```

then,there has error  :
```
/home/***/DEV/NodeProject/people_counting_statistics/node_modules/redis/index.js:710
    if (typeof command_obj.callback === 'function') {
                          ^

TypeError: Cannot read property 'callback' of undefined
    at normal_reply (/home/***/DEV/NodeProject/people_counting_statistics/node_modules/redis/index.js:710:27)
    at RedisClient.return_reply (/home/***/DEV/NodeProject/people_counting_statistics/node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.returnReply (/home/***/DEV/NodeProject/people_counting_statistics/node_modules/redis/index.js:188:18)
    at JavascriptRedisParser.execute (/home/***/DEV/NodeProject/people_counting_statistics/node_modules/redis-parser/lib/parser.js:491:12)
    at Socket.<anonymous> (/home/***/DEV/NodeProject/people_counting_statistics/node_modules/redis/index.js:267:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

**Comment by folletto** [comment]
Sorry but I don't know anything about Kue.

**Comment by frosty** [comment]
Same here I'm afraid.

**Comment by orangebook** [comment]
It it so shit,today I delete all code without kue,but when i reboot machine ,everything is ok.but when i add above code ,error again.but when i retry run code above ,ok.but i add above code with my express+Worker+Redis+Angular,error again.Oh my god.how get error before this error code

**Comment by orangebook** [comment]
@behrad

**Comment by orangebook** [comment]
I find it is Redis Error.KUE with Redis is OK.so  Ii go to here  NodeRedis/node_redis#1037
