### ISSUE TITLE
redis connection failed  ECONNREFUSED 

### ISSUE THREAD

**Issue by bitliner** [Automattic/kue#1003]
* Version `0.10.5`
* Node version `v6.9.1`

My code to handle connection is:

```
var jobs;

function start() {
        jobs = kue.createQueue({
                redis: {
                        host: REDIS_HOST,
                        port: REDIS_PORT
                }
        });
        jobs.client.on('error', function(err) {
                console.log('err', err);
        });
        jobs.shutdown(function() {
                        process.nextTick(function() {
                                start();
                        });
        });
}
start();
```

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 187.123.12.23:6379 failed - connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

**Comment by bitliner** [comment]
The strange thing is that error i not catched.
But as you can see, there is a callback to manage the error.

**Comment by bitliner** [comment]
It might be related to [this](https://github.com/NodeRedis/node_redis/issues/81)

**Comment by bitliner** [comment]
I will try the following way of overwriting the client, and I will try to better specify the options for redis client, according to https://github.com/NodeRedis/node_redis/issues/81

**Comment by behrad** [comment]
use `job.on('error', ...)` please
