### ISSUE TITLE
Shutdown not communicating to workers

### ISSUE THREAD

**Issue by BarryCarlyon** [Automattic/kue#1031]
I have a interface.js which basically jsut setups to the kue dashboard.

I have a seperate js say worker.js

I send a code 15 (aka SIGTERM) via `kill -15 PID` to the interface.js PID which then issues the `queue.shutdown()` which I would of thought `signals all workers to stop processing after their current active job is done.` but by worker.js just continues to munch on the queue.

Is there something I'm missing in worker.js to tell interface.js it's a worker?

**Comment by DevBrent** [comment]
I'm actually experiencing this problem when I call queue.shutdown myself. I've seen it work, but like other things in KUE it's not consistent. Processors continue to consume the queue despite the shutdown being requested two days ago.

**Comment by TheGrandmother** [comment]
I'm having problems with shutdown as well.
The example code from the readme does not seem to work.
I will be in touch if i can find a solution.

**Comment by osher** [comment]
downgrade to `kue@0.10.5` gave me this:
```
C:\ws\nodejs\fixport>node bin\ui
Kue-UI started on  { address: '::', family: 'IPv6', port: 3000 }
terminatation attempt #1
queue termination:  OK

events.js:160
      throw er; // Unhandled 'error' event
      ^
AbortError: LPUSH can't be processed. The connection is already closed.
    at handle_offline_command (C:\ws\nodejs\fixport\node_modules\redis\index.js:846:15)
    at RedisClient.internal_send_command (C:\ws\nodejs\fixport\node_modules\redis\index.js:880:9)
    at RedisClient.lpush (C:\ws\nodejs\fixport\node_modules\redis\lib\commands.js:62:25)
    at Command.callback (C:\ws\nodejs\fixport\node_modules\kue\lib\queue\worker.js:271:19)
    at normal_reply (C:\ws\nodejs\fixport\node_modules\redis\index.js:721:21)
    at RedisClient.return_reply (C:\ws\nodejs\fixport\node_modules\redis\index.js:819:9)
    at JavascriptRedisParser.returnReply (C:\ws\nodejs\fixport\node_modules\redis\index.js:192:18)
    at JavascriptRedisParser.execute (C:\ws\nodejs\fixport\node_modules\redis-parser\lib\parser.js:574:12)
    at Socket.<anonymous> (C:\ws\nodejs\fixport\node_modules\redis\index.js:274:27)
    at emitOne (events.js:96:13)
```

**Comment by osher** [comment]
downgrade to `kue@0.9.6` gave me:
```
C:\ws\nodejs\fixport>node bin\ui
Kue-UI started on  { address: '::', family: 'IPv6', port: 3000 }
terminatation attempt #1
queue termination:  OK
terminatation attempt #2
queue termination:  Shutdown already in progress

<I waited a VERY long time here>

terminatation attempt #3
C:\ws\nodejs\fixport\bin\ui.js:40
    if (!termAttempts) throw new Error('Hard Termination');
                       ^

Error: Hard Termination
    at process.terminate (C:\ws\nodejs\fixport\bin\ui.js:40:30)
    at emitNone (events.js:86:13)
    at process.emit (events.js:185:7)
    at Signal.wrap.onsignal (internal/process.js:199:44)
```

**Comment by osher** [comment]
downgrade to `kue@0.8.12` gave me this:
```
C:\ws\nodejs\fixport>node bin\ui
Kue-UI started on  { address: '::', family: 'IPv6', port: 3000 }
terminatation attempt #1
queue termination:  OK
TypeError: Cannot read property 'smembers' of null
    at Queue.types (C:\ws\nodejs\fixport\node_modules\kue\lib\kue.js:341:16)
    at exports.types (C:\ws\nodejs\fixport\node_modules\kue\lib\http\routes\json.js:58:11)
    at callbacks (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:161:37)
    at C:\ws\nodejs\fixport\node_modules\kue\lib\http\middleware\provides.js:11:39
    at callbacks (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:161:37)
    at param (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:135:11)
    at pass (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:142:5)
    at Router._dispatch (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:170:5)
    at Object.router (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:33:10)
    at next (C:\ws\nodejs\fixport\node_modules\express\node_modules\connect\lib\proto.js:190:15)
TypeError: Cannot read property 'zcard' of null
    at Queue.card (C:\ws\nodejs\fixport\node_modules\kue\lib\kue.js:400:16)
    at Queue.inactiveCount (C:\ws\nodejs\fixport\node_modules\kue\lib\kue.js:465:17)
    at _ (C:\ws\nodejs\fixport\node_modules\kue\lib\http\routes\json.js:294:25)
    at exports.stats (C:\ws\nodejs\fixport\node_modules\kue\lib\http\routes\json.js:41:9)
    at callbacks (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:161:37)
    at C:\ws\nodejs\fixport\node_modules\kue\lib\http\middleware\provides.js:11:39
    at callbacks (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:161:37)
    at param (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:135:11)
    at pass (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:142:5)
    at Router._dispatch (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:170:5)
terminatation attempt #2
queue termination:  Shutdown already in progress
TypeError: Cannot read property 'zcard' of null
    at Queue.card (C:\ws\nodejs\fixport\node_modules\kue\lib\kue.js:400:16)
    at Queue.inactiveCount (C:\ws\nodejs\fixport\node_modules\kue\lib\kue.js:465:17)
    at _ (C:\ws\nodejs\fixport\node_modules\kue\lib\http\routes\json.js:294:25)
    at exports.stats (C:\ws\nodejs\fixport\node_modules\kue\lib\http\routes\json.js:41:9)
    at callbacks (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:161:37)
    at C:\ws\nodejs\fixport\node_modules\kue\lib\http\middleware\provides.js:11:39
    at callbacks (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:161:37)
    at param (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:135:11)
    at pass (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:142:5)
    at Router._dispatch (C:\ws\nodejs\fixport\node_modules\express\lib\router\index.js:170:5)
terminatation attempt #3
C:\ws\nodejs\fixport\bin\ui.js:40
    if (!termAttempts) throw new Error('Hard Termination');
                       ^

Error: Hard Termination
    at process.terminate (C:\ws\nodejs\fixport\bin\ui.js:40:30)
    at emitNone (events.js:86:13)
    at process.emit (events.js:185:7)
    at Signal.wrap.onsignal (internal/process.js:199:44)
```
