### ISSUE TITLE
Kue connect to ec2 show up AbortError

### ISSUE THREAD

**Issue by Rukeith** [Automattic/kue#1056]
I build a redis with docker on AWS EC2. I use GUI tool and ping to public IP to make sure the redis works fine.But I use my node server to connect the redis, It will show AbortError like below. If I use local redis to replace, this error won't show up. How could I fix this?

```
13:51:52 1|server   | { AbortError
13:51:52 1|server   |     at RedisClient.flush_and_error (/Users/Project/node_modules/kue/node_modules/redis/index.js:357:23)
13:51:52 1|server   |     at RedisClient.connection_gone (/Users/Project/node_modules/kue/node_modules/redis/index.js:659:14)
13:51:52 1|server   |     at Socket.<anonymous> (/Users/Project/node_modules/kue/node_modules/redis/index.js:293:14)
13:51:52 1|server   |     at Object.onceWrapper (events.js:293:19)
13:51:52 1|server   |     at emitNone (events.js:91:20)
13:51:52 1|server   |     at Socket.emit (events.js:188:7)
13:51:52 1|server   |     at endReadableNT (_stream_readable.js:974:12)
13:51:52 1|server   |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
13:51:52 1|server   |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
13:51:52 1|server   |   code: 'UNCERTAIN_STATE',
13:51:52 1|server   |   command: 'BLPOP',
13:51:52 1|server   |   args: [ 'q:processSendEMail:jobs', 0 ] }

```

My Setting

```
let config = {
    port: process.env.EC2_REDIS_PORT,
    host: process.env.EC2_REDIS_HOST
  };
console.info(`OS : ${os.hostname()}, ip : ${ipaddr}`);
console.info('Redis config : ', config);

  queue = kue.createQueue({
    prefix: 'q',
    redis: config
  });
```

**Comment by behrad** [comment]
Talk to you AWS EC2 support and check the connection/network conditions to see why BLPOP keep alive connections to redis can't be made.
