### ISSUE TITLE
createQueue() gives Unhandled Exception error

### ISSUE THREAD

**Issue by gkrcode** [Automattic/kue#140]
``` javascript
kue = require 'kue'

try 
    jobs = kue.createQueue()
catch Err
    console.log "Caught : ",Err
```

gives unhandled error

```
events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/home/user/Documents/nodeex/node_modules/kue/node_modules/redis/index.js:140:24)
    at Socket.<anonymous> (/home/user/Documents/nodeex/node_modules/kue/node_modules/redis/index.js:74:14)
    at Socket.EventEmitter.emit (events.js:88:17)
    at Socket._destroy.self.errorEmitted (net.js:327:14)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

```

Am I missing something ?

**Comment by dandanknight** [comment]
Is the above code still valid? I'm having issues using this to catch the ECONNREFUSED error from the redis module. Thanks

**Comment by behrad** [comment]
actually not @dandanknight 
`queue.on( 'error', function(){})` should catch that for you

**Comment by dandanknight** [comment]
That works, many thanks.
