### ISSUE TITLE
Error: command failed

### ISSUE THREAD

**Issue by btmdave** [Automattic/kue#241]
Hello, I seem to be getting this when processing jobs:

```
Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)
```

Any idea what could be causing this?

Thank you!

**Comment by expresstechsoftwares** [comment]
Hey Did you solved this ? I'm trying queuing FFMPEG jobs but can't get it to make it happen. Any idea ? 

My sample code : 
var job = queue.create(exec(cmds), {
          title: 'welcome email for tj'
        , to: 'tj@learnboost.com'
        , template: 'welcome-email'
     }) 

But I'm not able to listing job events .
