### ISSUE TITLE
Cannot specify job type for queue count

### ISSUE THREAD

**Issue by ytilis** [Automattic/kue#558]
In the [Queue Maintenance](https://github.com/Automattic/kue#queue-maintenance) section of the README, the second example seems to fail due to too many arguments being passed.

For example:

    queue.completeCount('my-job-name', function( err, total ) {
      if( total > 10000 ) {
        console.log( 'This is tOoOo bad' );
      }
    });

When running the above, I get the following:

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: ERR wrong number of arguments for 'zcard' command
      at ReplyParser.<anonymous> (C:\Projects\...\node_modules\kue\node_modules\redis\index.js:305:31)
      at ReplyParser.EventEmitter.emit (events.js:95:17)
      at ReplyParser.send_error (C:\Projects\...\node_modules\kue\node_modules\redis\lib\parser\javascript.js:296:10)
      at ReplyParser.execute (C:\Projects\...\node_modules\kue\node_modules\redis\lib\parser\javascript.js:181:22)
      at RedisClient.on_data (C:\Projects\...\node_modules\kue\node_modules\redis\index.js:534:27)
      at Socket.<anonymous> (C:\Projects\...\node_modules\kue\node_modules\redis\index.js:91:14)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:699:14)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:382:10)
      at emitReadable (_stream_readable.js:377:5)
      at readableAddChunk (_stream_readable.js:142:7)
      at Socket.Readable.push (_stream_readable.js:112:10)
      at TCP.onread (net.js:496:21)
    
    >> application exited with code 8

Removing the job name, as below, causes it to work without error, albeit counting for all jobs rather than just the one I'm looking for:

    queue.completeCount(function( err, total ) {
      if( total > 10000 ) {
        console.log( 'This is tOoOo bad' );
      }
    });

**Comment by behrad** [comment]
which version are you? This is the latest kue docs, if you are on 0.8.x you should read https://github.com/Automattic/kue/tree/0.8#queue-maintenance

**Comment by ytilis** [comment]
I'm using whatever the latest version on npm is, but I was using the docs from master on the repo. I see now that the master docs do not match up with the latest doc which you linked to, which is also the README doc on npm. 

So is there no longer any way to get a count of completed tasks for a particular job outside of the JSON API? As that entire section seems to have been removed from the docs.

**Comment by behrad** [comment]
0.9.0 is the latest and is not release yet, so npm is not updated with it yet :)
you can install from master for now to check that feature in :)

**Comment by behrad** [comment]
> So is there no longer any way to get a count of completed tasks for a particular job outside of the JSON API?

`q.cardByType( 'my-job-type', 'complete', fn )`
