### ISSUE TITLE
ECONNRESET when max concurrency is hit

### ISSUE THREAD

**Issue by bogini** [Automattic/kue#569]
When more than the max number of concurrent jobs specified in `queue.process` are saved, I get the following error:

```
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
```

If I up the limit to more than the number of jobs created, there's no problem. From reading other issues I understand it works as a concurrency control rather than a rate limiter. 

How could I make the job wait until the queue can handle it?

**Comment by bogini** [comment]
For others having the same problem, you must implement your own rate limiter. More info here:

https://github.com/Automattic/kue/issues/441

**Comment by behrad** [comment]
`ECONNRESET` is not directly related to hitting concurrency.... Your redis server may be closing the connection.
Worker's concurrency is just a concurrency control which limits the total active jobs at the same time.

**Comment by bogini** [comment]
@behrad Why would that happen? I know it's not too many connections (only have 5 total ones).

**Comment by behrad** [comment]
Any connectivity problems? Check your redis server logs. and try to be more verbose in your code and see which party is closing the connection. You may also check issues on [node_redis](https://github.com/mranney/node_redis) to find out more.

**Comment by bogini** [comment]
Here's what I get when running `redis-server monitor`:

```
1428828406.175335 [0 127.0.0.1:60089] "publish" "q:events" "{\"id\":77,\"event\":\"enqueue\",\"args\":[\"enqueue\",\"jobtype1\"]}"
1428828406.176064 [0 127.0.0.1:60089] "hgetall" "q:job:77"
1428828406.301096 [0 127.0.0.1:59969] "MULTI"
1428828406.301505 [0 127.0.0.1:59969] "zrem" "q:jobs:inactive" "77"
1428828406.301519 [0 127.0.0.1:59969] "zrem" "q:jobs:jobtype1:inactive" "77"
1428828406.301527 [0 127.0.0.1:59969] "hset" "q:job:77" "state" "active"
1428828406.301535 [0 127.0.0.1:59969] "zadd" "q:jobs:active" "0" "77"
1428828406.301544 [0 127.0.0.1:59969] "zadd" "q:jobs:jobtype1:active" "0" "77"
1428828406.301557 [0 127.0.0.1:59969] "EXEC"
1428828406.425706 [0 127.0.0.1:59969] "hset" "q:job:77" "updated_at" "1428828406425"
1428828406.564650 [0 127.0.0.1:59972] "set" "promotion:lock" "c6/HMODwEeSZ/VHfjL9w+w==" "PX" "2000" "NX"
1428828406.565897 [0 127.0.0.1:59969] "zrangebyscore" "q:jobs:delayed" "0" "1428828406565" "LIMIT" "0" "1000"
1428828406.566705 [0 127.0.0.1:59972] "evalsha" "8797e0a1d8a2721e3b17f21ae1236166a81be165" "1" "promotion:lock" "c6/HMODwEeSZ/VHfjL9w+w=="
1428828406.566743 [0 lua] "get" "promotion:lock"
1428828406.566752 [0 lua] "del" "promotion:lock"
1428828406.651415 [0 127.0.0.1:59969] "incr" "q:ids"
1428828406.658339 [0 127.0.0.1:59969] "hset" "q:job:78" "max_attempts" "5"
1428828406.658400 [0 127.0.0.1:59969] "sadd" "q:job:types" "jobtype1"
1428828406.658420 [0 127.0.0.1:59969] "hset" "q:job:78" "type" "jobtype1"
1428828406.658440 [0 127.0.0.1:59969] "hset" "q:job:78" "created_at" "1428828406656"
1428828406.658457 [0 127.0.0.1:59969] "hset" "q:job:78" "promote_at" "1428828406656"
1428828406.658477 [0 127.0.0.1:59969] "hset" "q:job:78" "backoff" "{\"delay\":2000,\"type\":\"fixed\"}"
1428828406.658499 [0 127.0.0.1:59969] "hset" "q:job:78" "updated_at" "1428828406656"
1428828406.658517 [0 127.0.0.1:59969] "hset" "q:job:78" "priority" "0"
1428828406.658533 [0 127.0.0.1:59969] "zadd" "q:jobs" "0" "78"
1428828406.658562 [0 127.0.0.1:59969] "hset" "q:job:78" "data" "..."
1428828406.664422 [0 127.0.0.1:59969] "MULTI"
1428828406.664464 [0 127.0.0.1:59969] "hset" "q:job:78" "state" "inactive"
1428828406.664481 [0 127.0.0.1:59969] "zadd" "q:jobs:inactive" "0" "78"
1428828406.664499 [0 127.0.0.1:59969] "zadd" "q:jobs:jobtype1:inactive" "0" "78"
1428828406.664518 [0 127.0.0.1:59969] "lpush" "q:jobtype1:jobs" "1"
1428828406.664540 [0 127.0.0.1:59969] "EXEC"
1428828406.671310 [0 127.0.0.1:59969] "hset" "q:job:78" "updated_at" "1428828406669"
1428828406.674379 [0 127.0.0.1:60089] "publish" "q:events" "{\"id\":78,\"event\":\"enqueue\",\"args\":[\"enqueue\",\"jobtype1\"]}"
1428828406.676314 [0 127.0.0.1:59969] "MULTI"
1428828406.797492 [0 127.0.0.1:59969] "zrange" "q:jobs:jobtype1:inactive" "0" "0"
1428828406.797526 [0 127.0.0.1:59969] "zremrangebyrank" "q:jobs:jobtype1:inactive" "0" "0"
1428828406.797553 [0 127.0.0.1:59969] "EXEC"
1428828406.922935 [0 127.0.0.1:60089] "hgetall" "q:job:78"
1428828406.926936 [0 127.0.0.1:59969] "MULTI"
1428828406.927609 [0 127.0.0.1:59969] "zrem" "q:jobs:inactive" "78"
1428828406.927632 [0 127.0.0.1:59969] "zrem" "q:jobs:jobtype1:inactive" "78"
1428828406.927645 [0 127.0.0.1:59969] "hset" "q:job:78" "state" "active"
1428828406.927659 [0 127.0.0.1:59969] "zadd" "q:jobs:active" "0" "78"
1428828406.927673 [0 127.0.0.1:59969] "zadd" "q:jobs:jobtype1:active" "0" "78"
1428828406.927697 [0 127.0.0.1:59969] "EXEC"
1428828407.049647 [0 127.0.0.1:59969] "evalsha" "73a5f3c93bc373eb500cdb6e80ccca0220b89249" "0"
1428828407.049690 [0 lua] "keys" "q:jobs:*:inactive"
1428828407.175368 [0 127.0.0.1:59969] "hset" "q:job:78" "updated_at" "1428828407049"
1428828407.179789 [0 127.0.0.1:60089] "publish" "q:events" "{\"id\":\"78\",\"event\":\"error\",\"args\":[\"error\",\"Error: read ECONNRESET\\n    at errnoException (net.js:904:11)\\n    at TCP.onread (net.js:558:19)\"]}"
1428828407.298884 [0 127.0.0.1:59969] "hset" "q:job:78" "error" "Error: read ECONNRESET\n    at errnoException (net.js:904:11)\n    at TCP.onread (net.js:558:19)"
1428828407.298941 [0 127.0.0.1:59969] "rpush" "q:job:78:log" "Error: read ECONNRESET"
1428828407.298964 [0 127.0.0.1:59969] "hset" "q:job:78" "updated_at" "1428828407179"
1428828407.298983 [0 127.0.0.1:59969] "hset" "q:job:78" "failed_at" "1428828407179"
```

**Comment by bogini** [comment]
I'm also now getting this error:

```
node_modules/redis/index.js:602
                throw err;
                      ^
TypeError: object is not a function
    at Job.<anonymous> (node_modules/kue/lib/queue/job.js:572:16)
    at node_modules/redis/index.js:1170:13
    at try_callback (node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (node_modules/redis/index.js:321:14)
    at ReplyParser.emit (events.js:95:17)
    at ReplyParser.send_reply (node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (node_modules/redis/lib/parser/javascript.js:211:22)
    at RedisClient.on_data (node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (node_modules/redis/index.js:102:14)
```

**Comment by behrad** [comment]
Which version of Kue are you using?

**Comment by bogini** [comment]
I tried with both the repository's latest and the latest npm one.

**Comment by behrad** [comment]
there are breaking changes between the two, please test a single code with the compatible version first.
I haven't seen same error reported before.... You can also post me a code snippet generating this

**Comment by bogini** [comment]
Finally figured out why. I was failing jobs with `job.failed(error)` instead of `job.failed().error(error)`.

**Comment by behrad** [comment]
happy for you, however I can't see why are you calling `job.failed().error(error)` instead of `done(err)`. 
It can be losing your process context in your code, I advise you to pass `done` callback in your code contexts
