### ISSUE TITLE
TypeError: Uncaught, unspecified "error" event

### ISSUE THREAD

**Issue by jlertle** [Automattic/kue#571]
Hopefully you guys can help with this. I get this error every 3-4 days on high volume systems. 

    TypeError: Uncaught, unspecified "error" event.
        at TypeError (<anonymous>)
        at Worker.emit (events.js:74:15)
        at Worker.error (c:\path\app\node_modules\kue\lib\queue\worker.js:91:10)
        at C:\path\app\node_modules\kue\lib\queue\worker.js:67:23
        at Command.callback (c:\path\app\node_modules\kue\lib\queue\worker.js:249:20)
        at RedisClient.flush_and_error (c:\path\app\node_modules\kue\node_modules\redis\index.js:169:29)
        at RedisClient.connection_gone (c:\path\app\node_modules\kue\node_modules\redis\index.js:486:10)
        at Socket.<anonymous> (c:\path\app\node_modules\kue\node_modules\redis\index.js:110:14)
        at Socket.emit (events.js:95:17)
        at TCP.close (net.js:465:12)

I'm running Redis locally in memory only, no storage to disk, and Redis doesn't lose data so I do not think it's Redis.

I'm also bound to queue.on( 'error',...) but not getting anything reported there.

The infrequency of the issue and the fact that it only happens on high volume systems is making it hard to troubleshoot. Before I start debugging in production I figured I'd ask for ideas or suggestions.

**Comment by behrad** [comment]
weird! all, [that line](https://github.com/Automattic/kue/blob/master/lib/queue/worker.js#L91) is where I'm emitting errors into Worker's EventEmiter, however [here](https://github.com/Automattic/kue/blob/master/lib/kue.js#L260) Queue's are listening to worker's error event so that Uncaught doesn't happen and you can receive them on `queue.on(`error`)`

Could you add a trace log before https://github.com/Automattic/kue/blob/master/lib/queue/worker.js#L91 to print the error and stack trace when it happens :)

**Comment by jlertle** [comment]
I believe this is fixed by: https://github.com/Automattic/kue/commit/66dbab425199754ad963629d02170d6e7a8615d8
