### ISSUE TITLE
Master Branch 0.9.0, not .0.8.x, undeclared jade dependency?

### ISSUE THREAD

**Issue by paul42** [Automattic/kue#583]
Tried using kue from the master branch tarball, then tried to load up kue-ui and got this error:
Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at new View (C:\code\Impera\node_modules\express\lib\view.js:50:49)
    at EventEmitter.app.render (C:\code\Impera\node_modules\express\lib\application.js:545:12)
    at ServerResponse.res.render (C:\code\Impera\node_modules\express\lib\response.js:938:7)
    at C:\code\Impera\node_modules\kue\lib\http\routes\index.js:22:17
    at try_callback (C:\code\Impera\node_modules\redis\index.js:592:9)
    at RedisClient.return_reply (C:\code\Impera\node_modules\redis\index.js:685:13)

after doing a npm install jade the kue-ui works

I'm still a newbie, but if there's any way you could give me a rough outline I'd love to submit a pull request and help out :) it'd just be a simple as updating the package json of kue itself and adding a jade dependency, right?

**Comment by behrad** [comment]
the easiest way to install kue is `npm install kue` however if you are unpacking downloaded tar file, then you should cd in kue directory and run `npm install` so that all dependencies (including jade) be installed :)

**Comment by paul42** [comment]
ah, I see. I was eager for the latest branch for the delay logic fixes but npm only has .8.12, should I wait until your team is ready to publish .9. or is there a way to programmatically perform the npm install after I execute the command:  $ npm install http://github.com/Automattic/kue/tarball/master ?

Thanks again,
Paul

**Comment by behrad** [comment]
`$ npm install http://github.com/Automattic/kue/tarball/master` should work as mentioned [here](https://github.com/Automattic/kue#installation)
