### ISSUE TITLE
Crash on graceful shutdown

### ISSUE THREAD

**Issue by EgoAleSum** [Automattic/kue#606]
I noticed this error on my server's logs, while trying to shut down gracefully Kue:

````
worker-1 (err):     at Array.forEach (native)
worker-1 (err):     at Queue.shutdown (/home/ec2-user/app/src/node_modules/kue/lib/kue.js:406:18)
worker-1 (err):     at process.<anonymous> (/home/ec2-user/app/src/worker/server.js:129:10)
worker-1 (err):     at process.g (events.js:199:16)
worker-1 (err):     at process.emit (events.js:104:17)
worker-1 (err):     at Signal.wrap.onsignal (node.js:655:46)
worker-1 (err): 2015-05-06 14:43 +00:00: /home/ec2-user/app/src/node_modules/kue/lib/kue.js:384
worker-1 (err):       origFn.apply(null, arguments);
worker-1 (err):              ^
worker-1 (err): TypeError: undefined is not a function
worker-1 (err):     at fn (/home/ec2-user/app/src/node_modules/kue/lib/kue.js:384:14)
worker-1 (err):     at _fn (/home/ec2-user/app/src/node_modules/kue/lib/queue/worker.js:328:5)
worker-1 (err):     at Worker.shutdown (/home/ec2-user/app/src/node_modules/kue/lib/queue/worker.js:336:12)
worker-1 (err):     at /home/ec2-user/app/src/node_modules/kue/lib/kue.js:408:16
worker-1 (err):     at Array.forEach (native)
worker-1 (err):     at Queue.shutdown (/home/ec2-user/app/src/node_modules/kue/lib/kue.js:406:18)
worker-1 (err):     at process.<anonymous> (/home/ec2-user/app/src/worker/server.js:129:10)
worker-1 (err):     at process.g (events.js:199:16)
worker-1 (err):     at process.emit (events.js:104:17)
worker-1 (err):     at Signal.wrap.onsignal (node.js:655:46)
````

The code is:

````js
		// Support for graceful shutdown
		process.once('SIGTERM', function(sig) {
			var timeout = 5000 // Allow 5 seconds
			queue.shutdown(function(err) {
				console.log('Worker server is shut down', err || '')
				process.exit(0)
			}, timeout)
		})
````
The line that invokes the crashing code is `queue.shutdown`.

Node 0.12.2 on Amazon Linux.

**Comment by behrad** [comment]
on kue 0.9.X you should use shutdown as follows:

```js
queue.shutdown(timeout, function(err) {
  console.log('Worker server is shut down', err || '')
})
```

please read https://github.com/Automattic/kue/blob/master/History.md
I had no time to update wiki with a upgrade guide :(

**Comment by EgoAleSum** [comment]
Apologize for that, thanks

**Comment by behrad** [comment]
https://github.com/Automattic/kue/wiki/Upgrading-to-0.9.x

**Comment by EgoAleSum** [comment]
Thanks
