### ISSUE TITLE
Error: ERR unknown command 'blpop'

### ISSUE THREAD

**Issue by hiteshbalraw** [Automattic/kue#631]
Hi Team,

I am trying to add the job with some json data in kue but I am getting the below error.

Error: ERR unknown command 'blpop'
    at ReplyParser.<anonymous> (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:317:31)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_error (/var/data/test_app/node_modules/kue/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/var/data/test_app/node_modules/kue/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:102:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
Errorr in Kue :  Error: ERR unknown command 'blpop'
    at ReplyParser.<anonymous> (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:317:31)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_error (/var/data/test_app/node_modules/kue/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/var/data/test_app/node_modules/kue/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:102:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
Errorr in Kue :  Error: ERR unknown command 'blpop'
    at ReplyParser.<anonymous> (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:317:31)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_error (/var/data/test_app/node_modules/kue/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/var/data/test_app/node_modules/kue/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:102:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
Errorr in Kue :  Error: ERR unknown command 'blpop'
    at ReplyParser.<anonymous> (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:317:31)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_error (/var/data/test_app/node_modules/kue/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/var/data/test_app/node_modules/kue/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:102:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
node_redis: no callback to send error: ERR unknown command 'lpush'
node_redis: no callback to send error: ERR unknown command 'lpush'
node_redis: no callback to send error: ERR unknown command 'lpush'
node_redis: no callback to send error: ERR unknown command 'lpush'

/var/data/test_app/node_modules/kue/node_modules/redis/index.js:582
            throw err;
                  ^
Error: ERR unknown command 'lpush'
    at ReplyParser.<anonymous> (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:317:31)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_error (/var/data/test_app/node_modules/kue/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/var/data/test_app/node_modules/kue/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/var/data/test_app/node_modules/kue/node_modules/redis/index.js:102:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)

Please help.

**Comment by behrad** [comment]
strange... show your code :)

**Comment by behrad** [comment]
closed for inactivity. reopen if needed
