### ISSUE TITLE
blpop triggers the error when the connection is gone from end event

### ISSUE THREAD

**Issue by sunnychow** [Automattic/kue#690]
#### Step 1
We found that our machine is died when the connection is gone from end event
```
/deploy/.../node_modules/kue/node_modules/redis/index.js:172
                    throw callback_err;
                          ^
Error: Redis connection gone from end event.
    at RedisClient.flush_and_error (/deploy/.../node_modules/kue/node_modules/redis/index.js:149:13)
    at RedisClient.connection_gone (/deploy/.../node_modules/kue/node_modules/redis/index.js:486:10)
    at Socket.<anonymous> (/deploy/.../node_modules/kue/node_modules/redis/index.js:114:14)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:889:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickDomainCallback (node.js:385:17)
```

#### Step 2
As we want to know which command throws an error, so we changed the redis code to show the values during it's error
https://github.com/NodeRedis/node_redis/blob/master/index.js#L165
![](https://cloud.githubusercontent.com/assets/6318765/9117100/af3e2584-3c9a-11e5-9660-2808c0d21cd4.png)

And we found that the command is `blpop`
```
/deploy/.../node_modules/kue/node_modules/redis/index.js:179
                    throw callback_err;
                          ^
Error: Redis connection gone from end event. Thu Aug 06 2015 19:38:05 GMT+0800 (HKT) {
  "command": "blpop",
  "args": [
    "q:webhook:jobs",
    0
  ],
  "sub_command": false,
  "buffer_args": false
}
    at RedisClient.flush_and_error (/deploy/.../node_modules/kue/node_modules/redis/index.js:149:13)
    at RedisClient.connection_gone (/deploy/.../node_modules/kue/node_modules/redis/index.js:493:10)
    at Socket.<anonymous> (/deploy/.../node_modules/kue/node_modules/redis/index.js:114:14)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:889:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickDomainCallback (node.js:385:17)
```

#### Step 3
In Kue.js, they have called `blpop` command, and then it will call `lpush` command
https://github.com/Automattic/kue/blob/f7f89434d70bda794601fbeb3818ae39fcebc84c/lib/queue/worker.js#L269-L273
![](https://cloud.githubusercontent.com/assets/6318765/9117264/a398fd7a-3c9b-11e5-8222-4e60b78649dd.png)

#### Step 4
According to redis issue.
antirez/redis#2473
The issue happen when the instance role switch between master and slave
![](https://cloud.githubusercontent.com/assets/6318765/9117415/957cbfb4-3c9c-11e5-8783-901287094dec.png)

Luckily, The issue is fixed in 2.8.20
https://raw.githubusercontent.com/antirez/redis/2.8/00-RELEASENOTES

**Comment by sunnychow** [comment]
It's the problem on our application code. 
not related to Kue. 
Close it.
