### ISSUE TITLE
Error when job attempt fails

### ISSUE THREAD

**Issue by heri16** [Automattic/kue#733]
TypeError: Object #<Object> has no method 'emit'
    at C:\Users\ec2-user\cps-mailin\node_modules\kue\lib\queue\job.js:574:18
    at C:\Users\ec2-user\cps-mailin\node_modules\kue\lib\queue\job.js:542:24

**Comment by behrad** [comment]
send me your Kue and redis version and the code that produces this error please

**Comment by behrad** [comment]
any updates?
