### ISSUE TITLE
Error: LPUSH can't be processed. The connection has already been closed.

### ISSUE THREAD

**Issue by andrewtamura** [Automattic/kue#823]
Occasionally, usually when deploying, I get this redis error. 
```
Error: LPUSH can't be processed. The connection has already been closed.
    at RedisClient.send_command (/mnt/app/node_modules/redis/index.js:788:23)
    at RedisClient.(anonymous function).RedisClient.(anonymous function) (/mnt/app/node_modules/redis/index.js:966:25)
    at Command.callback (/mnt/app/node_modules/kue/lib/queue/worker.js:271:19)
    at RedisClient.return_reply (/mnt/app/node_modules/redis/index.js:664:25)
    at HiredisReplyParser.reply_parser.send_reply (/mnt/app/node_modules/redis/index.js:332:14)
    at HiredisReplyParser.execute (/mnt/app/node_modules/redis/lib/parsers/hiredis.js:30:18)
    at Socket.<anonymous> (/mnt/app/node_modules/redis/index.js:131:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

Looking at [worker.js#L271](https://github.com/Automattic/kue/blob/master/lib/queue/worker.js#L271), it appears that this redis call is missing a callback. I'm not sure what the correct behavior should be for the callback. If the LPUSH failure is like mine where the Redis connection is closed, we can't undo the BLPOP since we're no longer connected. At the least we should prevent pass a callback to this redis call to prevent an uncaught exception.

**Comment by behrad** [comment]
Can you create a PR to provide a callback and test this?

**Comment by zhdzmn** [comment]
This is occurring for me as well. I will try to get a PR soon.
