### ISSUE TITLE
TypeError: Cannot read property 'zcard' of null

### ISSUE THREAD

**Issue by andrewtamura** [Automattic/kue#825]
```
TypeError: Cannot read property 'zcard' of null
    at Queue.card (/Users/andrew/Code/send/node_modules/kue/lib/kue.js:513:14)
    at Queue.inactiveCount (/Users/andrew/Code/send/node_modules/kue/lib/kue.js:616:17)
    at _ (/Users/andrew/Code/send/node_modules/kue/lib/http/routes/json.js:318:19)
    at exports.stats (/Users/andrew/Code/send/node_modules/kue/lib/http/routes/json.js:41:3)
    at Layer.handle [as handle_request] (/Users/andrew/Code/send/node_modules/kue/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/andrew/Code/send/node_modules/kue/node_modules/express/lib/router/route.js:131:13)
    at /Users/andrew/Code/send/node_modules/kue/lib/http/middleware/provides.js:11:36
    at Layer.handle [as handle_request] (/Users/andrew/Code/send/node_modules/kue/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/andrew/Code/send/node_modules/kue/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/andrew/Code/send/node_modules/kue/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/andrew/Code/send/node_modules/kue/node_modules/express/lib/router/layer.js:95:5)
    at /Users/andrew/Code/send/node_modules/kue/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/andrew/Code/send/node_modules/kue/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/andrew/Code/send/node_modules/kue/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/Users/andrew/Code/send/node_modules/kue/node_modules/express/node_modules/serve-static/index.js:120:7)
    at emitOne (events.js:77:13)
    at SendStream.emit (events.js:169:7)
    at SendStream.error (/Users/andrew/Code/send/node_modules/kue/node_modules/express/node_modules/send/index.js:245:17)
    at SendStream.onStatError (/Users/andrew/Code/send/node_modules/kue/node_modules/express/node_modules/send/index.js:356:12)
    at next (/Users/andrew/Code/send/node_modules/kue/node_modules/express/node_modules/send/index.js:630:16)
    at onstat (/Users/andrew/Code/send/node_modules/kue/node_modules/express/node_modules/send/index.js:619:14)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

I get this error pretty consistently under the following conditions:
1. Have kui ui open in a browser window
2. perform graceful shutdown

I'm not certain if it is expected for Queue.client to be null. If it is, then `Queue.prototype.card` should first check if `this.client` exists before calling `this.client.card`. Same with `Queue.prototype.cardByType`

**Comment by narainsagar** [comment]
@andrewtamura Hi, I'm also getting the same for the case. Have you got this resolve? Thanks,

**Comment by bradvogel** [comment]
Answering on @andrewtamura 's behalf: we didn't resolve it. Instead, we moved over to Bull and all these problems disappeared.

**Comment by behrad** [comment]
> I'm not certain if it is expected for Queue.client to be null. If it is, then Queue.prototype.card should first check if this.client exists before calling this.client.card. Same with Queue.prototype.cardByType

exactly, after shutting down `this.client` is nullified

**Comment by narainsagar** [comment]
As, I wanted to have functionality to pause the processes so I figured out and got this done via `workers` `shutdown()` method and that nicely solved my problem.. 

below is some code:

```
var kue = require('kue');
/**
 * Wrapper of Kue queue
 */
class KueQueue extends EventEmitter {
  constructor(opts) {
    super();
    opts = _.defaults(opts || {}, {
      redis: config.get('redis'),
      prefix: ''
    });
    debug('creating queue %s', opts.redis);
    this.queue = kue.createQueue({prefix: opts.prefix, redis: opts.redis, jobEvents: false, disableSearch: false});
    this.queue.watchStuckJobs(1000);
}

stopWorkers() {
    return new Promise((resolve, reject) => {
      var length = this.queue.workers.length;
      queue.workers.forEach((worker) => {
        worker.shutdown(() => {
          if (--length === 0) {
            resolve();
          }
        });
      });
    });
  }
}

module.exports = KueQueue;

```
and then from `launcher.js`:

```
var debug = require('debug')('test:main:app');
var Queue = require('./queue/queue');
var isServerRunning = false;
var queue = new Queue();

exports.stop = function(success, failure) {
  return new Promise((resolve, reject) => {
    isServerRunning = false;
    queue.removeAllListeners();
    queue.stopWorkers().then(() => {
      debug('Queue stopped!!');
      resolve({success: true});
    });
  });
};
```
^ above the problem was axactly as @behrad had mentioned i.e., Queue.clientl` becomes `null` after shutdown() called..

hope this may help others!!

**Comment by behrad** [comment]
Thank you @narainsagar , Will try to fix this

**Comment by mmarshak** [comment]
Any update on this? I also see this error when the UI is connected?

@narainsagar I also get the error when the shutdown node only when the Kue UI is connected.
I log the value of queue.workers.length before the shutdown and it is zero. So I do not understand how your code solve the issue with the UI?

**Comment by narainsagar** [comment]
Hi @mmarshak ^ Sorry, I had used this library about a year ago, so I possibly can't re-call what & how it was exactly.. But Surely I will check it out if I finds that project (in which I used that code).

Thanks!

**Comment by mmarshak** [comment]
@narainsagar  Thanks!
