### ISSUE TITLE
 Redis connection lost and commands aborted in uncertain state

### ISSUE THREAD

**Issue by bartonhammond** [Automattic/kue#828]
I *think* this is from Kue as I don't use **ZRANGE**  in my code.

Please advise how I can get better logging and assist.

```
Running on OpenShift
Node Version: v4.2.3 
Redis Server: 2.18.24
Node_Redis: 2.4.2
```
error:
```
get /kue/getmapbox/d88d9c7f2879f4319f93be032a92a1326db12031/limetext/lime/ {} 200 (108439ms) 
160211/122622.552, [log,internal,implementation,error], data: {"code":"UNCERTAIN_STATE","command":"ZRANGE","domain":{"domain":null,"_events":{},"_eventsCount":1,"members":[]},"domainThrown":true}
Debug: internal, implementation, error 
    Error: Redis connection lost and commands aborted in uncertain state. They might have been processed.
    at RedisClient.connection_gone (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/node_modules/redis/index.js:569:17)
    at Socket.<anonymous> (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/node_modules/redis/index.js:144:14)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Redis connection to 56a388737628e1252200004b-bartonhammond.rhcloud.com:50681 failed - read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)
DEBUG: Program node build/server.js exited with code 1
DEBUG: Starting child process with 'node build/server.js'
Server is running: http://ex-std-node496.prod.rhcloud.com:8080
events.js:141

```

**Comment by behrad** [comment]
This is caused from a connection reset, Can you contact with OpenShift guys to check their Redis service !?

**Comment by bartonhammond** [comment]
@behrad will do!

**Comment by bartonhammond** [comment]
OpenShift recommended a larger Redis server...
