### ISSUE TITLE
origfn

### ISSUE THREAD

**Issue by giano** [Automattic/kue#869]
Hi, I've this error on graceful queue shutdown on version 0.10.5:

origfn is not a function 
Apr 27 08:29:59 test-air-alvieromartini app/web.2:  15:29:58 web-app-0 STACK: 
Apr 27 08:29:59 test-air-alvieromartini app/web.2:  15:29:58 web-app-0 TypeError: origFn is not a function 
Apr 27 08:29:59 test-air-alvieromartini app/web.2:  15:29:58 web-app-0   at Queue.shutdown (/app/node_modules/kue/lib/kue.js:423:5) 
Apr 27 08:29:59 test-air-alvieromartini app/web.2:  15:29:58 web-app-0   at process.<anonymous> (/app/workers/queue.js:14:18) 
Apr 27 08:29:59 test-air-alvieromartini app/web.2:  15:29:58 web-app-0   at process.g (events.js:260:16) 
Apr 27 08:29:59 test-air-alvieromartini app/web.2:  15:29:58 web-app-0   at emitNone (events.js:72:20) 
Apr 27 08:29:59 test-air-alvieromartini app/web.2:  15:29:58 web-app-0   at process.emit (events.js:166:7) 
Apr 27 08:29:59 test-air-alvieromartini app/web.2:  15:29:58 web-app-0   at Signal.wrap.onsignal (node.js:804:46) 

Seems to be a regression to [https://github.com/Automattic/kue/issues/606](https://github.com/Automattic/kue/issues/606)

**Comment by behrad** [comment]
If you check the code, it looks somehow wired!
Can you dig it more?

**Comment by giano** [comment]
Sorry for late response, didn't received the issue update message.

Yes, it seems to manage to "check" if there is something in "fn" length. But my case is managed in row 362, as I only pass timeout:

    process.once 'SIGTERM', (sig) -> queue.shutdown 5000

and kue consider the single parameter as callback. I can get along passing a fake callback function, so to go to row 366.

Can be fixed checking if first argument is a number or not, I think. Will fork and push the fix, if you want.

BTW: kue is very kool, it saved my bacon as I was using Parse Background Jobs and, as Parse is closing...

**Comment by behrad** [comment]
👍 a PR is welcome @giano

**Comment by giano** [comment]
Will work on it this weekend. Thanks for Kue.
