### ISSUE TITLE
Update node_redis

### ISSUE THREAD

**Issue by Paveltarno** [Automattic/kue#876]
Hello,
Are there any plans on updating node_redis version anytime soon?
Iv'e noticed in the last release (0.11.0) it's been locked to 2.4.x though the latest node_redis
release is currently 2.6.0-2 and has some desirable bug fixes.

Iv'e tried bumping the version in my own fork and though my app runs fine, not all Kue's tests pass:
```
  1) JOBS "after each" hook:
     Uncaught AbortError: LPUSH can't be processed. The connection is already closed.
    at handle_offline_command (node_modules/redis/index.js:851:15)
    at RedisClient.internal_send_command (node_modules/redis/index.js:884:9)
    at RedisClient.(anonymous function).RedisClient.(anonymous function) (node_modules/redis/lib/commands.js:45:25)
    at Command.callback (lib/queue/worker.js:272:21)
    at normal_reply (node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (node_modules/redis/index.js:823:9)
    at JavascriptReplyParser.Parser.returnReply (node_modules/redis/index.js:189:18)
    at JavascriptReplyParser.run (node_modules/redis-parser/lib/javascript.js:137:18)
    at JavascriptReplyParser.execute (node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (node_modules/redis/index.js:269:27)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
  

  2) JOBS "before each" hook:
     TypeError: Cannot read property 'call' of undefined
```
If it's desirable, I'd be happy to fix this and submit a PR with the latest node_redis stable version.
Also, If anyone knows about any inconsistencies between Kue and redis 2.6.x and can point me there it would be greatly appreciated.

**Comment by behrad** [comment]
I'm thinking to switch to ioredis, but a PR is more than welcome :)

**Comment by Paveltarno** [comment]
Are there any plans on submitting PR #877 soon?

**Comment by behrad** [comment]
merged
