### ISSUE TITLE
Automatic redis reconnect on timeout with exponential backoff?

### ISSUE THREAD

**Issue by olalonde** [Automattic/kue#879]
I'm sometimes getting

```javascript
19:27:12 worker.1         | events.js:160
19:27:12 worker.1         |       throw er; // Unhandled 'error' event
19:27:12 worker.1         |       ^
19:27:12 worker.1         |
19:27:12 worker.1         | Error: Redis connection to 192.168.99.100:6379 failed - read ETIMEDOUT
19:27:12 worker.1         |     at exports._errnoException (util.js:896:11)
19:27:12 worker.1         |     at TCP.onread (net.js:556:26)
```

out of nowhere when using kue. Shouldn't this module attempt to automatically reconnect (with exponential backoff) when redis emits this error? It feels like it should be the responsibility of this module to handle this error gracefully and perhaps throw an error if reconnect fails after multiple attempts.

**Comment by behrad** [comment]
It is actually the responsibility of node.js redis modules, and I believe both node_redis and ioredis do this! However there should be something wrong somewhere using them inside kue. I should check this.

**Comment by behrad** [comment]
#875

**Comment by Rukeith** [comment]
Is this fix?
