### ISSUE TITLE
Cluster workers not being able to pick up Jobs / double pick up

### ISSUE THREAD

**Issue by JperF** [Automattic/kue#918]
The following program will create two `cluster` workers, then one job task. The job task will be marked as failed immediately. Every second the job is marked back as `inactive` which should be picked up again by a single worker. However occasionally more than one worker is picking up the job cause it to be executed twice.  

Is there something wrong with my logic or is this an issue with the cluster implementation in `kue`? 

````javascript
var kue = require('kue');
var jobs = kue.createQueue();
var cluster = require('cluster');

if(cluster.isMaster){
    cluster.fork();
    cluster.fork();
    jobs.create('test').save();

    setInterval(function () {
        kue.Job.rangeByState( 'failed', 0, -1, 'asc', function( err, jobs ) {
            if(err){
                console.log(err);
            }
            else{
                jobs.forEach( function ( job ) {
                    job.state('inactive').save();
                });
            }
        });
    }, 1000);
}

if(cluster.isWorker){
    jobs.process('test', function ( job, done ) {
        console.log('worker' , cluster.worker.id + ' has control of: ' + job.id + ' | ' +  new Date());
        done('failed');
    });
}
else{
    jobs.on('job failed', function ( errorMessage ) {
        console.log('Job failed');
    })
}
````

**Comment by behrad** [comment]
Can you check this against v1 branch also?

**Comment by JperF** [comment]
@behrad Running the same program throws the following error:

````javascript
TypeError:  kue.Job.rangeByState is not a function
    at null._repeat (/Users/test/clusterTest.js:18:13)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
````

**Comment by behrad** [comment]
Sorry I've n't created a migration check list yes, `rangeByState` is moved to queue object :)

**Comment by JperF** [comment]
@behrad 

Changing to `kue.rangeByState(..)` throws an error as well.
````javascript
TypeError: kue.rangeByState is not a function
````

**Comment by behrad** [comment]
```
queue = createQueue()
queue.rangeByState...
```

**Comment by JperF** [comment]
Same problem is happening as I initially stated:

>  However occasionally more than one worker is picking up the job cause it to be executed twice.

Note that only a maximum of 2 workers ever pick up the job regardless of how many there are.

**Comment by JperF** [comment]
@behrad 
Has there been any process on this issue?

**Comment by victusfate** [comment]
To be clear, if workers are triggered from a stand alone proc ie node worker.js this is not an issue?

**Comment by victusfate** [comment]
Seeing this regularly now with 2 worker processes, v0.11.1, v0.11.2, and master. Haven't migrated to v1 yet to test

**Comment by victornikitin** [comment]
@JperF Have you found the solution?

**Comment by JperF** [comment]
Hey @victornikitin,

Unfortunately I have not looked into this for more than 2 years. So I am not sure where Kue's code stands nor if this is still an issue.
