### ISSUE TITLE
Kue on redis cluster doesn't follow moved directives

### ISSUE THREAD

**Issue by rhenretta** [Automattic/kue#941]
I have been running Kue on a single server with a redis instance, but needed to create a cluster for high availability.  I now have 3 servers, each with a master and 2 slave redis instances.  When creating my queue:

```javascript
var sync = require('./dcm_sync');`

var     kue = require('kue')
    ,   queue = kue.createQueue();
        
queue.process('dcm_sync', 5, function(job, done) {
    console.log('Picked up job from queue: ' + JSON.stringify(job.data));
    sync.process(job.data);
    done();
});
```

I get the following repeated over and over in my log:

> PM2 Starting execution sequence in -cluster mode- for app name:dcm_sync_worker id:6
> PM2 App name:dcm_sync_worker id:6 online
> dcm_sync_worker-6 ReplyError: MOVED 12461 10.175.10.184:6380
> dcm_sync_worker-6     at parseError (/srv/node/releases/20160902005535/node_modules/kue/node_modules/redis/node_modules/redis-parser/lib/parser.js:163:12)
> dcm_sync_worker-6     at parseType (/srv/node/releases/20160902005535/node_modules/kue/node_modules/redis/node_modules/redis-parser/lib/parser.js:224:14)
> PM2 App name:dcm_sync_worker id:6 disconnected
> PM2 App [dcm_sync_worker] with id [6] and pid [18670], exited with code [0] via signal [SIGINT]

**Comment by rhenretta** [comment]
Found the readme section about using ioredis.  Seems to work.
