### ISSUE TITLE
REST api - request entity too large

### ISSUE THREAD

**Issue by dynnamitt** [Automattic/kue#948]
Hi, I'm trying out Kue rest api via kue-dashboard ( docker image pavlov/kue-dashboard:latest )

My JSON is "above normal size" it seems since I get

    Error: request entity too large
    at IncomingMessage.onData (/node_modules/raw-body/index.js:286:12)
    at emitOne (events.js:90:13)
    at IncomingMessage.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at IncomingMessage.Readable.push (_stream_readable.js:111:10)
    at HTTPParser.parserOnBody (_http_common.js:124:22)

To get this error you just base64 encode files into the data section of the json request. And make sure the file is above 100k

If i grep kue I find

     node_modules/kue/node_modules/body-parser/lib/types/text.js:39:    ? bytes.parse(opts.limit || '100kb')
     node_modules/kue/node_modules/body-parser/lib/types/raw.js:37:    ? bytes.parse(opts.limit || '100kb')
     node_modules/kue/node_modules/body-parser/lib/types/json.js:54:    ? bytes.parse(opts.limit || '100kb')
     node_modules/kue/node_modules/body-parser/HISTORY.md:464:  * lower default limits to 100kb
     node_modules/kue/node_modules/body-parser/lib/types/urlencoded.js:54:    ? bytes.parse(opts.limit || '100kb')

**Q:**  Any ways to _modify_ these options if running binary **kue-dashboard**  ?

**Comment by dynnamitt** [comment]
the obvious answer must be no, since -h is not reporting this limit as a CLI option

    $ node_modules/.bin/kue-dashboard -h                                     1 ↵
    Usage: /home/kjetil/code/ds3g/gitlab-worker/node_modules/.bin/kue-dashboard
[options]

    Options:
      -r          Redis url                      [default: "redis://127.0.0.1:6379"]
      -p          Dashboard port                                     [default: 3000]
      -h, --help  Show help                                                [boolean]

**Comment by dynnamitt** [comment]
Any pull request window comming soon? .. there is a queue of them LOL

**Comment by dynnamitt** [comment]
Nevermind , I can solve it by following help text (creating my own bin) : '

    You can fire it up from within another application too:

    var kue = require('kue');
    kue.createQueue(...);
    kue.app.listen(3000);

Then maybe using proxyquire lib to get to the options if they are hard to reach...
